import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '../../providers/ThemeProvider';
import Header from 'ui/src/components/Header/Header';
import { availableLanguages, LanguageType } from 'ui/src/utils/interfaces';

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ru' }, { lang: 'ua' }];
}

export const metadata: Metadata = {
  title: 'Penny App',
  description: 'Generated by create next app', //TODO: to update
};

const normalizeLocale = (lang: string): LanguageType => {
  return availableLanguages.includes(lang as LanguageType) ? (lang as LanguageType) : 'en';
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang: rawLang } = await params;
  const lang = normalizeLocale(rawLang);

  return (
    <html lang={lang}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider>
            <Header lang={lang} />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
